export enum PermissionContextsEnum {
  DEFAULT = 'default',
  USERS = 'users',
  EXERCISE = 'exercises',
  PROGRAMS = 'programs',
  ACTIVITIES = 'activities',
  FINANCIAL_SOURCES = 'financialSources',
  ADDRESSES = 'addresses',
  STRUCTURE = 'structures',
  TECHNICAL_SUPERVISION = 'technicalSupervisions',
  PARAGRAPHS = 'paragraphs',
  ROLES = 'roles',
  ADMINISTRATIVE_UNITS = 'administrativeUnits',
  FUNCTIONS = 'functions',
  SUB_PROGRAMS = 'subPrograms',
  REFERENCE_PHYSICAL_UNITS = 'referencePhysicalUnits',
  CONTRIBUABLES = 'contribuables',
  REGIMES = 'regimes',
  AGENTS = 'agents',
  ARTICLES = 'articles',
  RUBRIQUES = 'rubriques',
  SOUS_RUBRIQUES = 'sousRubriques',
  CARNET_MANDATS = 'carnetsMandats',
  BAREMES_MISSIONS = 'baremes',
  PIECES_JOINTES = 'piecesJointes',
  TYPES_PROCEDURES = 'typesProcedures',
}

export enum UserAccountStatusEnum {
  ACTIVE = 'active',
  INACTIVE = 'inactive',
}
